# Generated by Django 2.2.3 on 2019-07-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbsblog', '0002_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
