# Generated by Django 2.2.3 on 2019-07-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbsblog', '0003_remove_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
    ]
