# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wewe', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', tinymce.models.HTMLField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('cell', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
