# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='company_owner',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cell',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
