# Generated by Django 2.2.3 on 2019-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbsapp', '0003_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.CharField(max_length=200, null=True, verbose_name='eg Airline'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
