# Generated by Django 2.2.3 on 2019-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbsapp', '0004_auto_20190708_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=60, null=True, verbose_name='link to linkedin profile'),
        ),
    ]
